apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oiv47h641-go
  janus-idp.io/tekton: oiv47h641-go
  backstage.io/kubernetes-id: oiv47h641-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oiv47h641-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
