apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oiv47h641-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oiv47h641-go 
  name: oiv47h641-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oiv47h641-go 
